name: Pruebas y Despliegue CI-CD
on: push
jobs:
  zap_scan:
      runs-on: ubuntu-latest
      name: Run DAST scan on the web application
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ci-cd
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.6.1
          with:
            docker_name: 'owasp/zap2docker-stable'
            target: 'http://example.com/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'
